---
- name: install nginx in target machine
  hosts: group
  become: yes
  vars: 
    port: 81
  tasks:
    - name: install nginx
      yum: 
       name: nginx
       state: present 
    - name: edit config file using template
      template:
        src: nginx.j2
        dest: /etc/nginx/nginx.conf
    - name: service restart
      service:
        name: nginx
        state: restarted
        
